---@diagnostic disable: missing-return
---@diagnostic disable: lowercase-global

--[[
    Needs review:
    onClientGUIDoubleClick
]]

---@alias addEventHandlerPriority "high" | "normal" | "low" | string
---@alias addEventHandler_generic fun(eventName: string, attachedTo: element, handlerFunction: function, getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserCreated fun(eventName: "onClientBrowserCreated", attachedTo: element, handlerFunction: function, getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserCursorChange fun(eventName: "onClientBrowserCursorChange", attachedTo: element, handlerFunction: fun(cursorId: integer), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserDocumentReady fun(eventName: "onClientBrowserDocumentReady", attachedTo: element, handlerFunction: fun(url: string), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserInputFocusChanged fun(eventName: "onClientBrowserInputFocusChanged", attachedTo: element, handlerFunction: fun(gainedFocus: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserLoadingFailed fun(eventName: "onClientBrowserLoadingFailed", attachedTo: element, handlerFunction: fun(url: string, errorCode: integer, errorDescription: string), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserLoadingStart fun(eventName: "onClientBrowserLoadingStart", attachedTo: element, handlerFunction: fun(url: string, isMain: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserNavigate fun(eventName: "onClientBrowserNavigate", attachedTo: element, handlerFunction: fun(targetURL: string, isBlocked: boolean, isMainFrame: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserPopup fun(eventName: "onClientBrowserPopup", attachedTo: element, handlerFunction: fun(targetURL: string, openerURL: string, isPopup: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserResourceBlocked fun(eventName: "onClientBrowserResourceBlocked", attachedTo: element, handlerFunction: fun(url: string, domain: string, reason: 0 | 1 | 2), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserTooltip fun(eventName: "onClientBrowserTooltip", attachedTo: element, handlerFunction: fun(text: string), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientBrowserWhitelistChange fun(eventName: "onClientBrowserWhitelistChange", attachedTo: element, handlerFunction: fun(changedDomains: string[]), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientColShapeHit fun(eventName: "onClientColShapeHit", attachedTo: element, handlerFunction: fun(theElement: element, matchingDimension: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientColShapeLeave fun(eventName: "onClientColShapeLeave", attachedTo: element, handlerFunction: fun(theElement: element, matchingDimension: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementColShapeHit fun(eventName: "onClientElementColShapeHit", attachedTo: element, handlerFunction: fun(theShape: colshape, matchingDimension: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementColShapeLeave fun(eventName: "onClientElementColShapeLeave", attachedTo: element, handlerFunction: fun(theShape: colshape, matchingDimension: boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementDataChange fun(eventName: "onClientElementDataChange", attachedTo: element, handlerFunction: fun(theKey: string, oldValue: unknown, newValue: unknown), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementDestroy fun(eventName: "onClientElementDestroy", attachedTo: element, handlerFunction: fun(), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementDimensionChange fun(eventName: "onClientElementDimensionChange", attachedTo: element, handlerFunction: fun(oldDimension: integer, newDimension: integer), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementInteriorChange fun(eventName: "onClientElementInteriorChange", attachedTo: element, handlerFunction: fun(oldInterior: integer, newInterior: integer), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementModelChange fun(eventName: "onClientElementModelChange", attachedTo: element, handlerFunction: fun(oldModel: integer, newModel: integer), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementStreamIn fun(eventName: "onClientElementStreamIn", attachedTo: element, handlerFunction: fun(), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientElementStreamOut fun(eventName: "onClientElementStreamOut", attachedTo: element, handlerFunction: fun(), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientCharacter fun(eventName: "onClientCharacter", attachedTo: element, handlerFunction: fun(character: string), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientClick fun(eventName: "onClientClick", attachedTo: element, handlerFunction: fun(button: mouseButton, state: "up" | "down", absoluteX: integer, absoluteY: integer, worldX: number, worldY: number, worldZ: number, clickedWorld: element | false), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientCursorMove fun(eventName: "onClientCursorMove", attachedTo: element, handlerFunction: fun(cursorX: number, cursorY: number, absoluteX: integer, absoluteY: integer, worldX: number, worldY: number, worldZ: number), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientDoubleClick fun(eventName: "onClientDoubleClick", attachedTo: element, handlerFunction: fun(button: mouseButton, absoluteX: integer, absoluteY: integer, worldX: number, worldY: number, worldZ: number, clickedWorld: element | false), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientKey fun(eventName: "onClientKey", attachedTo: element, handlerFunction: fun(button : keyName, pressOrRelease : boolean), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientPaste fun(eventName: "onClientPaste", attachedTo: element, handlerFunction: fun(clipboardText: string), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientGUIAccepted fun(eventName: "onClientGUIAccepted", attachedTo: element, handlerFunction: fun(editBox: element), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientGUIBlur fun(eventName: "onClientGUIBlur", attachedTo: element, handlerFunction: fun(), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientGUIChanged fun(eventName: "onClientGUIChanged", attachedTo: element, handlerFunction: fun(theElement : element), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientGUIClick fun(eventName: "onClientGUIClick", attachedTo: element, handlerFunction: fun(button: mouseButton, state: "down", absoluteX: integer, absoluteY: integer), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientGUIComboBoxAccepted fun(eventName: "onClientGUIComboBoxAccepted", attachedTo: element, handlerFunction: fun(theElement: element), getPropagated?: boolean, priority?: addEventHandlerPriority): boolean
---@alias addEventHandler_onClientGUIDoubleClick fun(eventName: "onClientGUIDoubleClick", attachedTo: element, handlerFunction: function, getPropagated?: boolean, priority?: addEventHandlerPriority): boolean


---@type addEventHandler_generic | addEventHandler_onClientGUIDoubleClick | addEventHandler_onClientGUIComboBoxAccepted | addEventHandler_onClientGUIClick | addEventHandler_onClientGUIChanged | addEventHandler_onClientGUIBlur | addEventHandler_onClientGUIAccepted | addEventHandler_onClientPaste | addEventHandler_onClientKey | addEventHandler_onClientDoubleClick | addEventHandler_onClientCursorMove | addEventHandler_onClientClick | addEventHandler_onClientCharacter | addEventHandler_onClientElementStreamOut | addEventHandler_onClientElementStreamIn | addEventHandler_onClientElementModelChange | addEventHandler_onClientElementInteriorChange | addEventHandler_onClientElementDimensionChange | addEventHandler_onClientElementDestroy | addEventHandler_onClientElementDataChange | addEventHandler_onClientElementColShapeLeave | addEventHandler_onClientElementColShapeHit | addEventHandler_onClientColShapeLeave | addEventHandler_onClientColShapeHit | addEventHandler_onClientBrowserWhitelistChange | addEventHandler_onClientBrowserTooltip | addEventHandler_onClientBrowserResourceBlocked | addEventHandler_onClientBrowserPopup | addEventHandler_onClientBrowserNavigate | addEventHandler_onClientBrowserLoadingStart | addEventHandler_onClientBrowserLoadingFailed | addEventHandler_onClientBrowserInputFocusChanged | addEventHandler_onClientBrowserDocumentReady | addEventHandler_onClientBrowserCreated | addEventHandler_onClientBrowserCursorChange
function addEventHandler () end
